// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type Environment struct {
	ID        int64     `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type EnvironmentValue struct {
	ID            int64     `db:"id" json:"id"`
	EnvironmentID int64     `db:"environment_id" json:"environment_id"`
	Key           string    `db:"key" json:"key"`
	Value         string    `db:"value" json:"value"`
	CreatedAt     time.Time `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time `db:"updated_at" json:"updated_at"`
}
