// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
)

type Querier interface {
	CreateEnvironment(ctx context.Context, name string) (Environment, error)
	CreateValue(ctx context.Context, arg CreateValueParams) (EnvironmentValue, error)
	DeleteEnvironment(ctx context.Context, id int64) error
	DeleteValue(ctx context.Context, id int64) error
	GetAllEnvironments(ctx context.Context) ([]Environment, error)
	GetAllValues(ctx context.Context) ([]EnvironmentValue, error)
	GetEnvironment(ctx context.Context, id int64) (Environment, error)
	GetEnvironmentByName(ctx context.Context, name string) (Environment, error)
	GetValue(ctx context.Context, id int64) (EnvironmentValue, error)
	GetValueByKey(ctx context.Context, arg GetValueByKeyParams) (EnvironmentValue, error)
	GetValuesByEnvironmentID(ctx context.Context, environmentID int64) ([]EnvironmentValue, error)
	UpdateValue(ctx context.Context, arg UpdateValueParams) (EnvironmentValue, error)
}

var _ Querier = (*Queries)(nil)
