apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: secretly-pvc
  namespace: secretly
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # Ajustar según tu cluster